apiVersion: v1
kind: Service
metadata:
    name: {{.Values.appname}}
spec:
    type: {{.Values.spec.type}}
    ports:
    - port: {{.Values.spec.port}}
    selector:
        app: {{.Values.appname}}